### PR TITLE
Enhancements to Batch Operations, Cost Estimation, and Identity Request

### PR DESCRIPTION
**Pull request by 71walceli**
This pull request introduces significant improvements:

* **Batch Operations:** Utilized the `Utilities.batch_all` function to efficiently perform batch operations, optimizing performance and reducing network overhead.
* **Cost Estimation:** Added functionality to estimate the costs associated with calls, providing users with valuable information before executing transactions (logged to console for now).
* **Identity Request Class:** Introduced the `identity.requestJudgement` call into the batch, enabling users to request judgments to verify their identity infor.

These enhancements contribute to a more efficient, informative, and user-friendly application, providing users with better control over their transactions and the identity verification process.

### CODE REVIEW

**Review by hitchho — COMMENTED** [review]
imo we should use 256 instead of 128 hashes since those are also used onchain.  i asked claude to codereview. just go through the points if those  are relevant or not. some we dont really care like UUIDs generation but f.g. first point sounds valid



Critical Issues:

1. Unprotected Timer Resource:
```typescript
let timer;
if (appStateSnapshot.account) {
  timer = setInterval(...
```
The timer variable is declared in function scope but used in closure. This should be managed via useRef to prevent closure issues across re-renders. Current implementation risks memory leaks and race conditions.

2. Unsafe Type Coercion:
```typescript
account = { ...account, ..._account }
```
Direct object spreading without type validation could lead to prototype pollution. Need explicit type validation and proper interface definition.

3. Unconstrained API Polling:
The CHAIN_UPDATE_INTERVAL is set to 6000ms with no backoff strategy. This could enable DoS conditions under load or network issues.

Significant Issues:

4. Unsafe Promise Chaining:
```typescript
(async () => {
  const data = getSubmitData();
  // ... batch transaction code
})()
```
The IIFE lacks error boundaries and proper cleanup. This could leave transactions in undefined states.

5. Missing State Validation:
```typescript
if (appStateSnap.account) {
  const _ss58Info = getSs58AddressInfo(appStateSnap.account.address);
```
No validation of address format before passing to getSs58AddressInfo. Could lead to undefined behavior with malformed addresses.

6. Cryptographic Operation Exposure:
```typescript
value: crypto.randomUUID()
```
Direct use of crypto.randomUUID() for challenge values without entropy validation. Should use a more robust source of randomness for security-critical operations.

Security Design Issues:

7. Identity Storage Pattern:
The identity storage uses Blake2128Concat without proper key derivation. This could enable certain theoretical timing attacks.

8. Unsafe Raw Identity Handling:
```typescript
interface IdentityInfo {
  display?: Uint8Array
  legal?: Uint8Array
  // ...
}
```
Direct exposure of raw Uint8Array without bounds checking or sanitization.

Recommendations:

1. Implement proper timer cleanup:
```typescript
const timerRef = useRef<number>();
useEffect(() => {
  if (appStateSnapshot.account) {
    timerRef.current = window.setInterval(() => {
      // ... 
    }, CHAIN_UPDATE_INTERVAL);
    return () => {
      if (timerRef.current) {
        window.clearInterval(timerRef.current);
      }
    };
  }
}, [appStateSnapshot.account]);
```

2. Add proper type validation:
```typescript
interface Account {
  address: string;
  // ... other required fields
}

const mergeAccounts = (stored: Account, current: Account): Account => {
  // Explicit validation and merging
}
```

3. Implement proper error boundaries around async operations:
```typescript
try {
  await batch.signSubmitAndWatch(/*...*/);
} catch (e) {
  // Proper error handling
} finally {
  // Cleanup
}
```

4. Add proper input validation:
```typescript
const validateAddress = (address: string): boolean => {
  // Implement proper SS58 validation
}
```

5. Use a proper CSPRNG wrapper:
```typescript
const getSecureRandomValue = (): string => {
  // Implement proper random generation with entropy checking
}
```

This PR introduces significant new attack surface through the identity management features. While the core functionality appears sound, the implementation needs hardening against several classes of attacks.

The batch transaction feature is particularly concerning from a security perspective - ensure proper transaction ordering and error handling is implemented.

Please address these issues before merging.

**Comment by hitchho** [comment]
whats still missing is the logic of using the hash

  ├── Hash Match?
  │   ├── No  -> Batch(SetIdentity + RequestJudgement)
  │   └── Yes -> Check Judgement
  │              ├── None -> Request Judgement
  │              ├── FeePaid -> Show Challenges (Page 2)
  │              ├── Reasonable -> Show Submission (Page 3)

**Comment by hitchho** [comment]
why is there folder HASHERS? we have folder for hooks

**Comment by 71walceli** [comment]
> imo we should use 256 instead of 128 hashes since those are also used onchain. i asked claude to codereview. just go through the points if those are relevant or not. some we dont really care like UUIDs generation but f.g. first point sounds valid

ok, but it seems to actually be using that, as suggested by identity.tsx:82, isn't it? Only in the idetitiyOf storage seems it's using `blake2128Concat`, which I'm addressing. Is it OK to use `blake3256` and `blake3256Concat`

**Comment by 71walceli** [comment]
> 
> Critical Issues:
> 
> 1. Unprotected Timer Resource:
> 
> ```ts
> let timer;
> if (appStateSnapshot.account) {
>   timer = setInterval(...
> ```

Addressed

**Comment by 71walceli** [comment]
> 6. Cryptographic Operation Exposure:
> 
> ```ts
> value: crypto.randomUUID()
> ```
> 
> Direct use of crypto.randomUUID() for challenge values without entropy validation. Should use a more robust source of randomness for security-critical operations.

Yeah, we get rid of this one by using challenges API, which required actually implementing conditions and validations.

**Comment by hitchho** [comment]
71walceli/rotko__w3registrar-www/tree/mvp1-implementingConditions

create pr with

**Pull request closed without merging**
